language: android
jdk:
  - oraclejdk8
sudo: false
android:
  components:
  - tools
  - tools  # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943
  - platform-tools
  - build-tools-24.0.1
  - android-24
  - extra-android-m2repository
  - extra-google-m2repository
  licenses:
  - android-sdk-license-.+
script:
- "./gradlew build check --daemon"
after_failure: "cat $TRAVIS_BUILD_DIR/app/build/outputs/lint-results-debug.xml"